# Generated by Django 5.1.1 on 2024-10-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_images/default_image.jpg', upload_to='course_images/'),
        ),
    ]
